load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "argsParser",
    hdrs = ["argsParser.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "senderWithPipe",
    srcs = ["senderWithPipe.cc"],
    hdrs = ["senderWithPipe.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "receiverWithPipe",
    srcs = ["receiverWithPipe.cc"],
    hdrs = ["receiverWithPipe.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "senderWithMsgq",
    srcs = ["senderWithMsgq.cc"],
    hdrs = ["senderWithMsgq.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "receiverWithMsgq",
    srcs = ["receiverWithMsgq.cc"],
    hdrs = ["receiverWithMsgq.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "senderWithShmem",
    srcs = ["senderWithShmem.cc"],
    hdrs = ["senderWithShmem.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "receiverWithShmem",
    srcs = ["receiverWithShmem.cc"],
    hdrs = ["receiverWithShmem.h"],
    visibility = ["//visibility:public"],
)