load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "senderWithPipe",
    srcs = ["senderWithPipe.cc"],
    hdrs = ["senderWithPipe.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "receiverWithPipe",
    srcs = ["receiverWithPipe.cc"],
    hdrs = ["receiverWithPipe.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "senderWithMq",
    srcs = ["senderWithMq.cc"],
    hdrs = ["senderWithMq.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "receiverWithMq",
    srcs = ["receiverWithMq.cc"],
    hdrs = ["receiverWithMq.h"],
    visibility = ["//visibility:public"],
)