cc_test(
  name = "senderWithPipe_test",
  size = "small",
  srcs = ["senderWithPipe_test.cc"],
  deps = [
    "@com_google_googletest//:gtest_main",
    "//src/main:sender",
    "//src/main:receiver",
    ],
)